trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Deploy
  jobs:
  - job: DeployViaAnsible
    steps:
    - task: CopyFilesOverSSH@0
      inputs:
        sshEndpoint: 'ansible-ssh'
        sourceFolder: '$(Build.SourcesDirectory)'
        contents: '**'
        targetFolder: '/home/azureuser/frontend'

    - task: SSH@0
      inputs:
        sshEndpoint: 'ansible-ssh'
        runOptions: inline
        inline: |
          ansible-playbook frontend.yml 

